"""add symbols repo_manifests import_kind is_test

Revision ID: 0757516bc461
Revises: 2c20265ab4ca
Create Date: 2026-08-23 11:01:56.671709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0757516bc461'
down_revision: Union[str, None] = '2c20265ab4ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repo_manifests',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('path_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['path_id'], ['repo_paths.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repo_manifests_repo_id'), 'repo_manifests', ['repo_id'], unique=False)
    op.create_table('symbols',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('path_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('line', sa.Integer(), nullable=False),
    sa.Column('exported', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['path_id'], ['repo_paths.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbols_repo_id'), 'symbols', ['repo_id'], unique=False)
    op.create_index('ix_symbols_repo_id_name', 'symbols', ['repo_id', 'name'], unique=False)
    # server_default required here, not just the ORM-level Python default --
    # dependencies/files are populated tables in any deployed environment,
    # and Postgres rejects adding a NOT NULL column with no default against
    # existing rows (plan/RULES.md sec 7). Dropped again once every existing
    # row has a concrete value, matching the ORM's Python-side default (new
    # rows never need the server default after this) -- same pattern as
    # migration 2c20265ab4ca's repos.is_private.
    op.add_column(
        'dependencies',
        sa.Column('import_kind', sa.String(), nullable=False, server_default=sa.text("'static'")),
    )
    op.alter_column('dependencies', 'import_kind', server_default=None)
    op.add_column(
        'files', sa.Column('is_test', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.alter_column('files', 'is_test', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'is_test')
    op.drop_column('dependencies', 'import_kind')
    op.drop_index('ix_symbols_repo_id_name', table_name='symbols')
    op.drop_index(op.f('ix_symbols_repo_id'), table_name='symbols')
    op.drop_table('symbols')
    op.drop_index(op.f('ix_repo_manifests_repo_id'), table_name='repo_manifests')
    op.drop_table('repo_manifests')
    # ### end Alembic commands ###
