"""add showcase, eviction tracking columns to repos

Revision ID: 14c6fede52b9
Revises: be4f3a061321
Create Date: 2026-09-02 18:36:51.395002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14c6fede52b9'
down_revision: Union[str, None] = 'be4f3a061321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # `repos` is a populated table (plan/RULES.md sec 7): is_showcase needs a
    # server default so the ADD COLUMN ... NOT NULL doesn't fail against
    # existing rows, dropped again once applied (session 03's is_test/
    # session 07's churn_weighted precedent -- see that migration's own
    # server_default-then-drop dance).
    op.add_column(
        'repos', sa.Column('is_showcase', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.add_column('repos', sa.Column('showcase_rank', sa.Integer(), nullable=True))
    op.add_column('repos', sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('repos', sa.Column('facts_evicted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('repos', 'is_showcase', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repos', 'facts_evicted_at')
    op.drop_column('repos', 'last_viewed_at')
    op.drop_column('repos', 'showcase_rank')
    op.drop_column('repos', 'is_showcase')
    # ### end Alembic commands ###
