"""add tour_stops glossary_terms repo_passport

Revision ID: 2751f5757bd2
Revises: 2ec74771930c
Create Date: 2026-08-23 22:02:32.001247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2751f5757bd2'
down_revision: Union[str, None] = '2ec74771930c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('glossary_terms',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('term', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('occurrences', sa.Integer(), nullable=False),
    sa.Column('subsystem_spread', sa.Integer(), nullable=False),
    sa.Column('defining_path_ids', postgresql.ARRAY(sa.BigInteger()), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_glossary_terms_analysis_run_id'), 'glossary_terms', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_glossary_terms_repo_id'), 'glossary_terms', ['repo_id'], unique=False)
    op.create_table('repo_passport',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('onboarding_difficulty', sa.Float(), nullable=False),
    sa.Column('difficulty_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repo_passport_analysis_run_id'), 'repo_passport', ['analysis_run_id'], unique=True)
    op.create_index(op.f('ix_repo_passport_repo_id'), 'repo_passport', ['repo_id'], unique=False)
    op.create_table('tour_stops',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('path_id', sa.BigInteger(), nullable=False),
    sa.Column('reason_code', sa.Text(), nullable=False),
    sa.Column('reason_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('subsystem_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['path_id'], ['repo_paths.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subsystem_id'], ['subsystems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_run_id', 'position', name='uq_tour_stops_run_id_position')
    )
    op.create_index(op.f('ix_tour_stops_analysis_run_id'), 'tour_stops', ['analysis_run_id'], unique=False)
    op.create_index('ix_tour_stops_repo_id', 'tour_stops', ['repo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tour_stops_repo_id', table_name='tour_stops')
    op.drop_index(op.f('ix_tour_stops_analysis_run_id'), table_name='tour_stops')
    op.drop_table('tour_stops')
    op.drop_index(op.f('ix_repo_passport_repo_id'), table_name='repo_passport')
    op.drop_index(op.f('ix_repo_passport_analysis_run_id'), table_name='repo_passport')
    op.drop_table('repo_passport')
    op.drop_index(op.f('ix_glossary_terms_repo_id'), table_name='glossary_terms')
    op.drop_index(op.f('ix_glossary_terms_analysis_run_id'), table_name='glossary_terms')
    op.drop_table('glossary_terms')
    # ### end Alembic commands ###
