"""add contributors file_expertise truck_factor

Revision ID: 2ec74771930c
Revises: b577d24da72f
Create Date: 2026-08-23 15:53:14.655626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ec74771930c'
down_revision: Union[str, None] = 'b577d24da72f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contributors',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('canonical_email', sa.Text(), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('commit_count', sa.Integer(), nullable=False),
    sa.Column('lines_added', sa.Integer(), nullable=False),
    sa.Column('lines_deleted', sa.Integer(), nullable=False),
    sa.Column('first_commit_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_commit_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('active_days', sa.Integer(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contributors_analysis_run_id', 'contributors', ['analysis_run_id'], unique=False)
    op.create_index('ix_contributors_repo_id', 'contributors', ['repo_id'], unique=False)
    op.create_table('truck_factor',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('removal_order', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_files_considered', sa.Integer(), nullable=False),
    sa.Column('orphaned_file_count', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_truck_factor_analysis_run_id'), 'truck_factor', ['analysis_run_id'], unique=True)
    op.create_table('file_expertise',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('path_id', sa.BigInteger(), nullable=False),
    sa.Column('contributor_id', sa.BigInteger(), nullable=False),
    sa.Column('doa', sa.Float(), nullable=False),
    sa.Column('doa_normalized', sa.Float(), nullable=False),
    sa.Column('is_expert', sa.Boolean(), nullable=False),
    sa.Column('changes', sa.Integer(), nullable=False),
    sa.Column('last_touched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contributor_id'], ['contributors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['path_id'], ['repo_paths.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_file_expertise_run_id_path_id', 'file_expertise', ['analysis_run_id', 'path_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_file_expertise_run_id_path_id', table_name='file_expertise')
    op.drop_table('file_expertise')
    op.drop_index(op.f('ix_truck_factor_analysis_run_id'), table_name='truck_factor')
    op.drop_table('truck_factor')
    op.drop_index('ix_contributors_repo_id', table_name='contributors')
    op.drop_index('ix_contributors_analysis_run_id', table_name='contributors')
    op.drop_table('contributors')
    # ### end Alembic commands ###
