"""add health table

Revision ID: 43b7ca24e69c
Revises: dd6f42fefe57
Create Date: 2026-07-25 21:02:58.076434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43b7ca24e69c'
down_revision: Union[str, None] = 'dd6f42fefe57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('high_risk_ratio', sa.Float(), nullable=False),
    sa.Column('cycle_count', sa.Integer(), nullable=False),
    sa.Column('hidden_dependency_count', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_repo_id'), 'health', ['repo_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_health_repo_id'), table_name='health')
    op.drop_table('health')
    # ### end Alembic commands ###
