"""add narratives table

Revision ID: 669314f7bda5
Revises: c442dfaaf8b0
Create Date: 2026-09-02 06:36:47.248809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '669314f7bda5'
down_revision: Union[str, None] = 'c442dfaaf8b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('narratives',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('surface', sa.Text(), nullable=False),
    sa.Column('subject_key', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('factpack_hash', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_run_id', 'surface', 'subject_key', name='uq_narratives_run_surface_subject')
    )
    op.create_index(op.f('ix_narratives_analysis_run_id'), 'narratives', ['analysis_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_narratives_analysis_run_id'), table_name='narratives')
    op.drop_table('narratives')
    # ### end Alembic commands ###
