"""initial schema

Revision ID: 70017ee3b25d
Revises:
Create Date: 2026-09-04 00:36:37.252695

Hand-adjusted after autogenerate (plan/REBUILD.md §3.4, session prompt step
4): autogenerate ordered `analysis_runs` before `repos`, but the two have a
genuine circular foreign-key relationship (`analysis_runs.repo_id ->
repos.id` and `repos.current_run_id -> analysis_runs.id`) that Postgres
cannot satisfy in a single `CREATE TABLE` pass either way round. Fixed by
creating `users` -> `repos` (without its `current_run_id` FK) ->
`analysis_runs`, then adding the `repos.current_run_id` FK as a separate
`ALTER TABLE` once both tables exist. `downgrade()` reverses this: drop the
added FK first, then the tables in the same relative order autogenerate
would have produced. Nothing else in this file was hand-edited -- every
other table's column list, index, and constraint is exactly what
`alembic revision --autogenerate` produced from `app/db/models.py`.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70017ee3b25d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('github_id', sa.BigInteger(), nullable=False),
    sa.Column('github_login', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('access_token_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('token_scopes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    # repos.current_run_id -> analysis_runs.id is a genuine circular FK
    # (analysis_runs.repo_id -> repos.id too) -- the constraint is added
    # separately, below, once both tables exist. See the module docstring.
    op.create_table('repos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('default_branch', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'mining', 'analyzing', 'ready', 'failed', name='repo_status'), nullable=False),
    sa.Column('commit_count', sa.Integer(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('head_sha', sa.Text(), nullable=True),
    sa.Column('current_run_id', sa.UUID(), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('visibility_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_showcase', sa.Boolean(), nullable=False),
    sa.Column('showcase_rank', sa.Integer(), nullable=True),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('facts_evicted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repos_owner_user_id'), 'repos', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_repos_url'), 'repos', ['url'], unique=True)
    op.create_table('analysis_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('running', 'ready', 'failed', 'superseded', name='analysis_run_status'), nullable=False),
    sa.Column('head_sha', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('engine_version', sa.Integer(), nullable=False),
    sa.Column('coupling_low_confidence', sa.Boolean(), nullable=True),
    sa.Column('worker_mode', sa.Text(), nullable=True),
    sa.Column('triggered_by_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_runs_repo_id'), 'analysis_runs', ['repo_id'], unique=False)
    op.create_index('ix_analysis_runs_repo_id_started_at', 'analysis_runs', ['repo_id', 'started_at'], unique=False)
    op.create_foreign_key('fk_repos_current_run_id_analysis_runs', 'repos', 'analysis_runs', ['current_run_id'], ['id'], ondelete='SET NULL')
    op.create_table('baselines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('size_bucket', sa.String(), nullable=False),
    sa.Column('p10', sa.Float(), nullable=False),
    sa.Column('p25', sa.Float(), nullable=False),
    sa.Column('p50', sa.Float(), nullable=False),
    sa.Column('p75', sa.Float(), nullable=False),
    sa.Column('p90', sa.Float(), nullable=False),
    sa.Column('n_repos', sa.Integer(), nullable=True),
    sa.Column('n_files', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('osv_cache',
    sa.Column('osv_id', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('osv_id')
    )
    op.create_table('analysis_stages',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'done', 'failed', 'skipped', name='stage_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'name', name='uq_analysis_stages_run_id_name')
    )
    op.create_index(op.f('ix_analysis_stages_run_id'), 'analysis_stages', ['run_id'], unique=False)
    op.create_table('commits',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('sha', sa.String(), nullable=False),
    sa.Column('author_name', sa.String(), nullable=False),
    sa.Column('author_email', sa.String(), nullable=False),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_fix', sa.Boolean(), nullable=False),
    sa.Column('is_revert', sa.Boolean(), nullable=False),
    sa.Column('fix_confidence', sa.Float(), nullable=False),
    sa.Column('files_changed', sa.Integer(), nullable=False),
    sa.Column('insertions', sa.Integer(), nullable=False),
    sa.Column('deletions', sa.Integer(), nullable=False),
    sa.Column('changed_path_ids', postgresql.ARRAY(sa.Integer()), server_default=sa.text("'{}'::integer[]"), nullable=False),
    sa.Column('added_lines', postgresql.ARRAY(sa.Integer()), server_default=sa.text("'{}'::integer[]"), nullable=False),
    sa.Column('deleted_lines', postgresql.ARRAY(sa.Integer()), server_default=sa.text("'{}'::integer[]"), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commits_repo_id'), 'commits', ['repo_id'], unique=False)
    op.create_index('ix_commits_repo_id_sha', 'commits', ['repo_id', 'sha'], unique=False)
    op.create_index(op.f('ix_commits_sha'), 'commits', ['sha'], unique=False)
    op.create_table('contributors',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('canonical_email', sa.Text(), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('commit_count', sa.Integer(), nullable=False),
    sa.Column('lines_added', sa.Integer(), nullable=False),
    sa.Column('lines_deleted', sa.Integer(), nullable=False),
    sa.Column('first_commit_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_commit_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('active_days', sa.Integer(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contributors_analysis_run_id', 'contributors', ['analysis_run_id'], unique=False)
    op.create_index('ix_contributors_repo_id', 'contributors', ['repo_id'], unique=False)
    op.create_table('glossary_terms',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('term', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('occurrences', sa.Integer(), nullable=False),
    sa.Column('subsystem_spread', sa.Integer(), nullable=False),
    sa.Column('defining_path_ids', postgresql.ARRAY(sa.BigInteger()), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_glossary_terms_analysis_run_id'), 'glossary_terms', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_glossary_terms_repo_id'), 'glossary_terms', ['repo_id'], unique=False)
    op.create_table('health',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('high_risk_ratio', sa.Float(), nullable=False),
    sa.Column('cycle_count', sa.Integer(), nullable=False),
    sa.Column('hidden_dependency_count', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_analysis_run_id'), 'health', ['analysis_run_id'], unique=True)
    op.create_index(op.f('ix_health_repo_id'), 'health', ['repo_id'], unique=False)
    op.create_table('hygiene_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('commit_sha', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('severity_hint', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hygiene_events_analysis_run_id', 'hygiene_events', ['analysis_run_id'], unique=False)
    op.create_index('ix_hygiene_events_repo_id', 'hygiene_events', ['repo_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=True),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'done', 'failed', name='job_status'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_repo_id'), 'jobs', ['repo_id'], unique=False)
    op.create_table('narratives',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('surface', sa.Text(), nullable=False),
    sa.Column('subject_key', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('factpack_hash', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_run_id', 'surface', 'subject_key', name='uq_narratives_run_surface_subject')
    )
    op.create_index(op.f('ix_narratives_analysis_run_id'), 'narratives', ['analysis_run_id'], unique=False)
    op.create_table('repo_passport',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('onboarding_difficulty', sa.Float(), nullable=False),
    sa.Column('difficulty_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repo_passport_analysis_run_id'), 'repo_passport', ['analysis_run_id'], unique=True)
    op.create_index(op.f('ix_repo_passport_repo_id'), 'repo_passport', ['repo_id'], unique=False)
    op.create_table('repo_paths',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id', 'path', name='uq_repo_paths_repo_id_path')
    )
    op.create_index(op.f('ix_repo_paths_repo_id'), 'repo_paths', ['repo_id'], unique=False)
    op.create_table('share_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_links_run_id'), 'share_links', ['run_id'], unique=False)
    op.create_index(op.f('ix_share_links_slug'), 'share_links', ['slug'], unique=True)
    op.create_table('snapshots',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('commit_sha', sa.Text(), nullable=False),
    sa.Column('at_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('commit_index', sa.Integer(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_run_id', 'position', name='uq_snapshots_run_id_position')
    )
    op.create_index(op.f('ix_snapshots_analysis_run_id'), 'snapshots', ['analysis_run_id'], unique=False)
    op.create_index('ix_snapshots_repo_id', 'snapshots', ['repo_id'], unique=False)
    op.create_table('subsystems',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('label_source', sa.Text(), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('total_loc', sa.Integer(), nullable=False),
    sa.Column('internal_edges', sa.Integer(), nullable=False),
    sa.Column('external_edges', sa.Integer(), nullable=False),
    sa.Column('cohesion', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_subsystems_analysis_run_id', 'subsystems', ['analysis_run_id'], unique=False)
    op.create_index('ix_subsystems_repo_id', 'subsystems', ['repo_id'], unique=False)
    op.create_table('truck_factor',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('removal_order', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_files_considered', sa.Integer(), nullable=False),
    sa.Column('orphaned_file_count', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_truck_factor_analysis_run_id'), 'truck_factor', ['analysis_run_id'], unique=True)
    op.create_table('vulnerabilities',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('ecosystem', sa.Text(), nullable=False),
    sa.Column('package_name', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('osv_id', sa.Text(), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('fixed_version', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_direct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vulnerabilities_analysis_run_id', 'vulnerabilities', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_repo_id'), 'vulnerabilities', ['repo_id'], unique=False)
    op.create_table('coupling',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('path_a_id', sa.BigInteger(), nullable=False),
    sa.Column('path_b_id', sa.BigInteger(), nullable=False),
    sa.Column('shared_revs', sa.Integer(), nullable=False),
    sa.Column('coupling_degree', sa.Float(), nullable=False),
    sa.Column('avg_revs', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['path_a_id'], ['repo_paths.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['path_b_id'], ['repo_paths.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupling_repo_id'), 'coupling', ['repo_id'], unique=False)
    op.create_index('ix_coupling_repo_id_degree', 'coupling', ['repo_id', 'coupling_degree'], unique=False)
    op.create_index('ix_coupling_run_id', 'coupling', ['analysis_run_id'], unique=False)
    op.create_table('dependencies',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('from_path_id', sa.BigInteger(), nullable=False),
    sa.Column('to_path_id', sa.BigInteger(), nullable=False),
    sa.Column('dep_type', sa.String(), nullable=False),
    sa.Column('import_kind', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['from_path_id'], ['repo_paths.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_path_id'], ['repo_paths.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependencies_repo_id'), 'dependencies', ['repo_id'], unique=False)
    op.create_table('dependencies_declared',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('ecosystem', sa.Text(), nullable=False),
    sa.Column('package_name', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=True),
    sa.Column('is_direct', sa.Boolean(), nullable=False),
    sa.Column('manifest_path_id', sa.BigInteger(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['manifest_path_id'], ['repo_paths.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependencies_declared_repo_id'), 'dependencies_declared', ['repo_id'], unique=False)
    op.create_table('entry_points',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('path_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['path_id'], ['repo_paths.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_entry_points_analysis_run_id', 'entry_points', ['analysis_run_id'], unique=False)
    op.create_index('ix_entry_points_repo_id', 'entry_points', ['repo_id'], unique=False)
    op.create_table('file_expertise',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('path_id', sa.BigInteger(), nullable=False),
    sa.Column('contributor_id', sa.BigInteger(), nullable=False),
    sa.Column('doa', sa.Float(), nullable=False),
    sa.Column('doa_normalized', sa.Float(), nullable=False),
    sa.Column('is_expert', sa.Boolean(), nullable=False),
    sa.Column('changes', sa.Integer(), nullable=False),
    sa.Column('last_touched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contributor_id'], ['contributors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['path_id'], ['repo_paths.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_file_expertise_run_id_path_id', 'file_expertise', ['analysis_run_id', 'path_id'], unique=False)
    op.create_table('file_metrics',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('path_id', sa.BigInteger(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_confidence', sa.Float(), nullable=True),
    sa.Column('hotspot_rank', sa.Integer(), nullable=True),
    sa.Column('instability_score', sa.Float(), nullable=True),
    sa.Column('revert_cycle_count', sa.Integer(), nullable=True),
    sa.Column('oversized_commit_count', sa.Integer(), nullable=True),
    sa.Column('fixup_commit_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['path_id'], ['repo_paths.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_run_id', 'path_id', name='uq_file_metrics_run_id_path_id')
    )
    op.create_index(op.f('ix_file_metrics_analysis_run_id'), 'file_metrics', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_file_metrics_repo_id'), 'file_metrics', ['repo_id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('path_id', sa.BigInteger(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('current_loc', sa.Integer(), nullable=False),
    sa.Column('complexity', sa.Float(), nullable=False),
    sa.Column('churn_total', sa.Integer(), nullable=False),
    sa.Column('commit_count', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('is_test', sa.Boolean(), nullable=False),
    sa.Column('churn_recent_365d', sa.Integer(), nullable=False),
    sa.Column('churn_weighted', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['path_id'], ['repo_paths.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_repo_id'), 'files', ['repo_id'], unique=False)
    op.create_index('ix_files_repo_id_path', 'files', ['repo_id', 'path'], unique=False)
    op.create_index('ix_files_repo_id_path_id', 'files', ['repo_id', 'path_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('severity', sa.Enum('low', 'med', 'high', name='finding_severity'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('path_id', sa.BigInteger(), nullable=True),
    sa.Column('evidence_sha', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['path_id'], ['repo_paths.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_analysis_run_id'), 'findings', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_findings_repo_id'), 'findings', ['repo_id'], unique=False)
    op.create_index('ix_findings_run_id_signature', 'findings', ['analysis_run_id', 'signature'], unique=False)
    op.create_table('module_coupling',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('granularity', sa.Text(), nullable=False),
    sa.Column('module_a', sa.Text(), nullable=False),
    sa.Column('module_b', sa.Text(), nullable=False),
    sa.Column('subsystem_a_id', sa.BigInteger(), nullable=True),
    sa.Column('subsystem_b_id', sa.BigInteger(), nullable=True),
    sa.Column('shared_revs', sa.Integer(), nullable=False),
    sa.Column('coupling_degree', sa.Float(), nullable=False),
    sa.Column('avg_revs', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subsystem_a_id'], ['subsystems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subsystem_b_id'], ['subsystems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_module_coupling_repo_id', 'module_coupling', ['repo_id'], unique=False)
    op.create_index('ix_module_coupling_run_id_granularity_degree', 'module_coupling', ['analysis_run_id', 'granularity', 'coupling_degree'], unique=False)
    op.create_table('repo_manifests',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('path_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['path_id'], ['repo_paths.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repo_manifests_repo_id'), 'repo_manifests', ['repo_id'], unique=False)
    op.create_table('secret_hits',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('path_id', sa.BigInteger(), nullable=True),
    sa.Column('commit_sha', sa.Text(), nullable=False),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('fingerprint', sa.Text(), nullable=False),
    sa.Column('redacted_preview', sa.Text(), nullable=True),
    sa.Column('entropy', sa.Float(), nullable=True),
    sa.Column('still_in_head', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['path_id'], ['repo_paths.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id', 'fingerprint', 'commit_sha', name='uq_secret_hits_repo_fingerprint_commit')
    )
    op.create_index(op.f('ix_secret_hits_repo_id'), 'secret_hits', ['repo_id'], unique=False)
    op.create_table('subsystem_members',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('subsystem_id', sa.BigInteger(), nullable=False),
    sa.Column('path_id', sa.BigInteger(), nullable=False),
    sa.Column('centrality', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['path_id'], ['repo_paths.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subsystem_id'], ['subsystems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subsystem_id', 'path_id', name='uq_subsystem_members_subsystem_id_path_id')
    )
    op.create_index(op.f('ix_subsystem_members_subsystem_id'), 'subsystem_members', ['subsystem_id'], unique=False)
    op.create_table('symbols',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('path_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('line', sa.Integer(), nullable=False),
    sa.Column('exported', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['path_id'], ['repo_paths.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbols_repo_id'), 'symbols', ['repo_id'], unique=False)
    op.create_index('ix_symbols_repo_id_name', 'symbols', ['repo_id', 'name'], unique=False)
    op.create_table('tour_stops',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('path_id', sa.BigInteger(), nullable=False),
    sa.Column('reason_code', sa.Text(), nullable=False),
    sa.Column('reason_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('subsystem_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['path_id'], ['repo_paths.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subsystem_id'], ['subsystems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_run_id', 'position', name='uq_tour_stops_run_id_position')
    )
    op.create_index(op.f('ix_tour_stops_analysis_run_id'), 'tour_stops', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_tour_stops_repo_id'), 'tour_stops', ['repo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tour_stops_repo_id'), table_name='tour_stops')
    op.drop_index(op.f('ix_tour_stops_analysis_run_id'), table_name='tour_stops')
    op.drop_table('tour_stops')
    op.drop_index('ix_symbols_repo_id_name', table_name='symbols')
    op.drop_index(op.f('ix_symbols_repo_id'), table_name='symbols')
    op.drop_table('symbols')
    op.drop_index(op.f('ix_subsystem_members_subsystem_id'), table_name='subsystem_members')
    op.drop_table('subsystem_members')
    op.drop_index(op.f('ix_secret_hits_repo_id'), table_name='secret_hits')
    op.drop_table('secret_hits')
    op.drop_index(op.f('ix_repo_manifests_repo_id'), table_name='repo_manifests')
    op.drop_table('repo_manifests')
    op.drop_index('ix_module_coupling_run_id_granularity_degree', table_name='module_coupling')
    op.drop_index('ix_module_coupling_repo_id', table_name='module_coupling')
    op.drop_table('module_coupling')
    op.drop_index('ix_findings_run_id_signature', table_name='findings')
    op.drop_index(op.f('ix_findings_repo_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_analysis_run_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index('ix_files_repo_id_path_id', table_name='files')
    op.drop_index('ix_files_repo_id_path', table_name='files')
    op.drop_index(op.f('ix_files_repo_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_file_metrics_repo_id'), table_name='file_metrics')
    op.drop_index(op.f('ix_file_metrics_analysis_run_id'), table_name='file_metrics')
    op.drop_table('file_metrics')
    op.drop_index('ix_file_expertise_run_id_path_id', table_name='file_expertise')
    op.drop_table('file_expertise')
    op.drop_index('ix_entry_points_repo_id', table_name='entry_points')
    op.drop_index('ix_entry_points_analysis_run_id', table_name='entry_points')
    op.drop_table('entry_points')
    op.drop_index(op.f('ix_dependencies_declared_repo_id'), table_name='dependencies_declared')
    op.drop_table('dependencies_declared')
    op.drop_index(op.f('ix_dependencies_repo_id'), table_name='dependencies')
    op.drop_table('dependencies')
    op.drop_index('ix_coupling_run_id', table_name='coupling')
    op.drop_index('ix_coupling_repo_id_degree', table_name='coupling')
    op.drop_index(op.f('ix_coupling_repo_id'), table_name='coupling')
    op.drop_table('coupling')
    op.drop_index(op.f('ix_vulnerabilities_repo_id'), table_name='vulnerabilities')
    op.drop_index('ix_vulnerabilities_analysis_run_id', table_name='vulnerabilities')
    op.drop_table('vulnerabilities')
    op.drop_index(op.f('ix_truck_factor_analysis_run_id'), table_name='truck_factor')
    op.drop_table('truck_factor')
    op.drop_index('ix_subsystems_repo_id', table_name='subsystems')
    op.drop_index('ix_subsystems_analysis_run_id', table_name='subsystems')
    op.drop_table('subsystems')
    op.drop_index('ix_snapshots_repo_id', table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_analysis_run_id'), table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_index(op.f('ix_share_links_slug'), table_name='share_links')
    op.drop_index(op.f('ix_share_links_run_id'), table_name='share_links')
    op.drop_table('share_links')
    op.drop_index(op.f('ix_repo_paths_repo_id'), table_name='repo_paths')
    op.drop_table('repo_paths')
    op.drop_index(op.f('ix_repo_passport_repo_id'), table_name='repo_passport')
    op.drop_index(op.f('ix_repo_passport_analysis_run_id'), table_name='repo_passport')
    op.drop_table('repo_passport')
    op.drop_index(op.f('ix_narratives_analysis_run_id'), table_name='narratives')
    op.drop_table('narratives')
    op.drop_index(op.f('ix_jobs_repo_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_hygiene_events_repo_id', table_name='hygiene_events')
    op.drop_index('ix_hygiene_events_analysis_run_id', table_name='hygiene_events')
    op.drop_table('hygiene_events')
    op.drop_index(op.f('ix_health_repo_id'), table_name='health')
    op.drop_index(op.f('ix_health_analysis_run_id'), table_name='health')
    op.drop_table('health')
    op.drop_index(op.f('ix_glossary_terms_repo_id'), table_name='glossary_terms')
    op.drop_index(op.f('ix_glossary_terms_analysis_run_id'), table_name='glossary_terms')
    op.drop_table('glossary_terms')
    op.drop_index('ix_contributors_repo_id', table_name='contributors')
    op.drop_index('ix_contributors_analysis_run_id', table_name='contributors')
    op.drop_table('contributors')
    op.drop_index(op.f('ix_commits_sha'), table_name='commits')
    op.drop_index('ix_commits_repo_id_sha', table_name='commits')
    op.drop_index(op.f('ix_commits_repo_id'), table_name='commits')
    op.drop_table('commits')
    op.drop_index(op.f('ix_analysis_stages_run_id'), table_name='analysis_stages')
    op.drop_table('analysis_stages')
    op.drop_table('osv_cache')
    op.drop_table('baselines')
    op.drop_constraint('fk_repos_current_run_id_analysis_runs', 'repos', type_='foreignkey')
    op.drop_index('ix_analysis_runs_repo_id_started_at', table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_repo_id'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index(op.f('ix_repos_url'), table_name='repos')
    op.drop_index(op.f('ix_repos_owner_user_id'), table_name='repos')
    op.drop_table('repos')
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
    # Hand-added: autogenerate's downgrade() drops every TABLE that uses a
    # native Postgres enum column but never the enum TYPE itself (a known
    # Alembic/Postgres limitation -- op.drop_table() does not imply DROP
    # TYPE, since the same type could in principle back more than one
    # column). Without these, a downgrade-then-upgrade cycle fails with
    # "type already exists" the moment upgrade() tries to CREATE TYPE again
    # -- caught by this migration's own verification (alembic upgrade /
    # downgrade base / upgrade head / check), not assumed.
    sa.Enum(name='repo_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='job_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='finding_severity').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='analysis_run_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='stage_status').drop(op.get_bind(), checkfirst=True)
