"""add hygiene_events, blast-radius-adjacent columns, risk v2

Revision ID: 84bd3d9014df
Revises: 2751f5757bd2
Create Date: 2026-08-24 10:55:41.252203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84bd3d9014df'
down_revision: Union[str, None] = '2751f5757bd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hygiene_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('commit_sha', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('severity_hint', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hygiene_events_analysis_run_id', 'hygiene_events', ['analysis_run_id'], unique=False)
    op.create_index('ix_hygiene_events_repo_id', 'hygiene_events', ['repo_id'], unique=False)
    # NOT NULL columns on populated tables (commits/files already have rows)
    # need a server_default for the ALTER TABLE itself -- autogenerate
    # omits it (it only knows the Python-side default), same precedent as
    # migrations 0757516bc461/2c20265ab4ca. Dropped again right after, once
    # every existing row has a concrete value, so it doesn't linger as a
    # permanent DB-side default the ORM model doesn't declare.
    op.add_column('commits', sa.Column('fix_confidence', sa.Float(), nullable=False, server_default='0'))
    op.add_column('file_metrics', sa.Column('instability_score', sa.Float(), nullable=True))
    op.add_column('file_metrics', sa.Column('revert_cycle_count', sa.Integer(), nullable=True))
    op.add_column('file_metrics', sa.Column('oversized_commit_count', sa.Integer(), nullable=True))
    op.add_column('file_metrics', sa.Column('fixup_commit_count', sa.Integer(), nullable=True))
    op.add_column('file_metrics', sa.Column('test_classification', sa.Text(), nullable=True))
    op.add_column('file_metrics', sa.Column('test_cochange_ratio', sa.Float(), nullable=True))
    op.add_column('file_metrics', sa.Column('mapped_test_path_ids', postgresql.ARRAY(sa.BigInteger()), nullable=True))
    op.add_column('files', sa.Column('churn_recent_365d', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('files', sa.Column('churn_weighted', sa.Float(), nullable=False, server_default='0'))
    op.alter_column('commits', 'fix_confidence', server_default=None)
    op.alter_column('files', 'churn_recent_365d', server_default=None)
    op.alter_column('files', 'churn_weighted', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'churn_weighted')
    op.drop_column('files', 'churn_recent_365d')
    op.drop_column('file_metrics', 'mapped_test_path_ids')
    op.drop_column('file_metrics', 'test_cochange_ratio')
    op.drop_column('file_metrics', 'test_classification')
    op.drop_column('file_metrics', 'fixup_commit_count')
    op.drop_column('file_metrics', 'oversized_commit_count')
    op.drop_column('file_metrics', 'revert_cycle_count')
    op.drop_column('file_metrics', 'instability_score')
    op.drop_column('commits', 'fix_confidence')
    op.drop_index('ix_hygiene_events_repo_id', table_name='hygiene_events')
    op.drop_index('ix_hygiene_events_analysis_run_id', table_name='hygiene_events')
    op.drop_table('hygiene_events')
    # ### end Alembic commands ###
