"""add subsystems entry_points module_coupling

Revision ID: b577d24da72f
Revises: 0757516bc461
Create Date: 2026-08-23 12:42:47.334850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b577d24da72f'
down_revision: Union[str, None] = '0757516bc461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subsystems',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('label_source', sa.Text(), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('total_loc', sa.Integer(), nullable=False),
    sa.Column('internal_edges', sa.Integer(), nullable=False),
    sa.Column('external_edges', sa.Integer(), nullable=False),
    sa.Column('cohesion', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_subsystems_analysis_run_id', 'subsystems', ['analysis_run_id'], unique=False)
    op.create_index('ix_subsystems_repo_id', 'subsystems', ['repo_id'], unique=False)
    op.create_table('entry_points',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('path_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['path_id'], ['repo_paths.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_entry_points_analysis_run_id', 'entry_points', ['analysis_run_id'], unique=False)
    op.create_index('ix_entry_points_repo_id', 'entry_points', ['repo_id'], unique=False)
    op.create_table('module_coupling',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('granularity', sa.Text(), nullable=False),
    sa.Column('module_a', sa.Text(), nullable=False),
    sa.Column('module_b', sa.Text(), nullable=False),
    sa.Column('subsystem_a_id', sa.BigInteger(), nullable=True),
    sa.Column('subsystem_b_id', sa.BigInteger(), nullable=True),
    sa.Column('shared_revs', sa.Integer(), nullable=False),
    sa.Column('coupling_degree', sa.Float(), nullable=False),
    sa.Column('avg_revs', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subsystem_a_id'], ['subsystems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subsystem_b_id'], ['subsystems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_module_coupling_repo_id', 'module_coupling', ['repo_id'], unique=False)
    op.create_index('ix_module_coupling_run_id_granularity_degree', 'module_coupling', ['analysis_run_id', 'granularity', 'coupling_degree'], unique=False)
    op.create_table('subsystem_members',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('subsystem_id', sa.BigInteger(), nullable=False),
    sa.Column('path_id', sa.BigInteger(), nullable=False),
    sa.Column('centrality', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['path_id'], ['repo_paths.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subsystem_id'], ['subsystems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subsystem_id', 'path_id', name='uq_subsystem_members_subsystem_id_path_id')
    )
    op.create_index(op.f('ix_subsystem_members_subsystem_id'), 'subsystem_members', ['subsystem_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subsystem_members_subsystem_id'), table_name='subsystem_members')
    op.drop_table('subsystem_members')
    op.drop_index('ix_module_coupling_run_id_granularity_degree', table_name='module_coupling')
    op.drop_index('ix_module_coupling_repo_id', table_name='module_coupling')
    op.drop_table('module_coupling')
    op.drop_index('ix_entry_points_repo_id', table_name='entry_points')
    op.drop_index('ix_entry_points_analysis_run_id', table_name='entry_points')
    op.drop_table('entry_points')
    op.drop_index('ix_subsystems_repo_id', table_name='subsystems')
    op.drop_index('ix_subsystems_analysis_run_id', table_name='subsystems')
    op.drop_table('subsystems')
    # ### end Alembic commands ###
