"""add queued status, portfolio_cache, baseline corpus counts

Revision ID: be4f3a061321
Revises: dd1fa16f1b9b
Create Date: 2026-09-02 15:05:36.206524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be4f3a061321'
down_revision: Union[str, None] = 'dd1fa16f1b9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Session 14, Known Hazard #1: adding a value to a Postgres native enum
    # requires an explicit ALTER TYPE ... ADD VALUE -- autogenerate never
    # produces this (it has no representation of "value added to an existing
    # enum type" in its diff). On Postgres, a newly-added enum value cannot
    # be referenced in the SAME transaction that added it, so this runs in
    # its own autocommit block, separate from the rest of this migration's
    # DDL below (plan/RULES.md sec 7).
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE analysis_run_status ADD VALUE IF NOT EXISTS 'queued'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_cache',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.add_column('analysis_runs', sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('baselines', sa.Column('n_repos', sa.Integer(), nullable=True))
    op.add_column('baselines', sa.Column('n_files', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('baselines', 'n_files')
    op.drop_column('baselines', 'n_repos')
    op.drop_column('analysis_runs', 'queued_at')
    op.drop_table('portfolio_cache')
    # ### end Alembic commands ###

    # NOTE: the 'queued' value added to analysis_run_status above is NOT
    # removed here. Postgres has no ALTER TYPE ... DROP VALUE -- removing a
    # value requires rebuilding the whole enum type (create a new type,
    # migrate every column using it, drop the old type, rename), which is
    # unsafe to do generically in a downgrade that doesn't know whether any
    # row is currently using the value. Per plan/RULES.md sec 7 ("every
    # migration must be reversible, or state in a comment why it cannot
    # be"): downgrading past this migration leaves the enum type with one
    # extra, unused value -- harmless (Postgres tolerates unused enum
    # members indefinitely) and the same trade-off every other Postgres
    # project with additive enum migrations makes.
