"""add secret_hits dependencies_declared vulnerabilities osv_cache

Revision ID: c442dfaaf8b0
Revises: 84bd3d9014df
Create Date: 2026-08-25 00:56:47.736465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c442dfaaf8b0'
down_revision: Union[str, None] = '84bd3d9014df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('osv_cache',
    sa.Column('osv_id', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('osv_id')
    )
    op.create_table('vulnerabilities',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('ecosystem', sa.Text(), nullable=False),
    sa.Column('package_name', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('osv_id', sa.Text(), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('fixed_version', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_direct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vulnerabilities_analysis_run_id'), 'vulnerabilities', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_repo_id'), 'vulnerabilities', ['repo_id'], unique=False)
    op.create_table('dependencies_declared',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('ecosystem', sa.Text(), nullable=False),
    sa.Column('package_name', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=True),
    sa.Column('is_direct', sa.Boolean(), nullable=False),
    sa.Column('manifest_path_id', sa.BigInteger(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['manifest_path_id'], ['repo_paths.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependencies_declared_repo_id'), 'dependencies_declared', ['repo_id'], unique=False)
    op.create_table('secret_hits',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('path_id', sa.BigInteger(), nullable=True),
    sa.Column('commit_sha', sa.Text(), nullable=False),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('fingerprint', sa.Text(), nullable=False),
    sa.Column('redacted_preview', sa.Text(), nullable=True),
    sa.Column('entropy', sa.Float(), nullable=True),
    sa.Column('still_in_head', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['path_id'], ['repo_paths.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id', 'fingerprint', 'commit_sha', name='uq_secret_hits_repo_fingerprint_commit')
    )
    op.create_index('ix_secret_hits_repo_id', 'secret_hits', ['repo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_secret_hits_repo_id', table_name='secret_hits')
    op.drop_table('secret_hits')
    op.drop_index(op.f('ix_dependencies_declared_repo_id'), table_name='dependencies_declared')
    op.drop_table('dependencies_declared')
    op.drop_index(op.f('ix_vulnerabilities_repo_id'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_analysis_run_id'), table_name='vulnerabilities')
    op.drop_table('vulnerabilities')
    op.drop_table('osv_cache')
    # ### end Alembic commands ###
