"""add coupling_low_confidence, worker_mode, findings.signature

Revision ID: c738e176e086
Revises: 07b31ed0e304
Create Date: 2026-08-22 17:04:38.444166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c738e176e086'
down_revision: Union[str, None] = '07b31ed0e304'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_runs', sa.Column('coupling_low_confidence', sa.Boolean(), nullable=True))
    op.add_column('analysis_runs', sa.Column('worker_mode', sa.Text(), nullable=True))
    op.add_column('findings', sa.Column('signature', sa.Text(), nullable=True))
    op.create_index('ix_findings_run_id_signature', 'findings', ['analysis_run_id', 'signature'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_findings_run_id_signature', table_name='findings')
    op.drop_column('findings', 'signature')
    op.drop_column('analysis_runs', 'worker_mode')
    op.drop_column('analysis_runs', 'coupling_low_confidence')
    # ### end Alembic commands ###
