"""add snapshots table

Revision ID: dd1fa16f1b9b
Revises: 669314f7bda5
Create Date: 2026-09-02 13:34:42.073046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd1fa16f1b9b'
down_revision: Union[str, None] = '669314f7bda5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snapshots',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('commit_sha', sa.Text(), nullable=False),
    sa.Column('at_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('commit_index', sa.Integer(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_run_id', 'position', name='uq_snapshots_run_id_position')
    )
    op.create_index(op.f('ix_snapshots_analysis_run_id'), 'snapshots', ['analysis_run_id'], unique=False)
    op.create_index('ix_snapshots_repo_id', 'snapshots', ['repo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_snapshots_repo_id', table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_analysis_run_id'), table_name='snapshots')
    op.drop_table('snapshots')
    # ### end Alembic commands ###
