"""initial release-a schema

Revision ID: dd6f42fefe57
Revises: 
Create Date: 2026-07-25 14:18:13.662099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd6f42fefe57'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baselines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('size_bucket', sa.String(), nullable=False),
    sa.Column('p10', sa.Float(), nullable=False),
    sa.Column('p25', sa.Float(), nullable=False),
    sa.Column('p50', sa.Float(), nullable=False),
    sa.Column('p75', sa.Float(), nullable=False),
    sa.Column('p90', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('default_branch', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'mining', 'analyzing', 'ready', 'failed', name='repo_status'), nullable=False),
    sa.Column('commit_count', sa.Integer(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repos_url'), 'repos', ['url'], unique=True)
    op.create_table('commits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('sha', sa.String(), nullable=False),
    sa.Column('author_name', sa.String(), nullable=False),
    sa.Column('author_email', sa.String(), nullable=False),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_fix', sa.Boolean(), nullable=False),
    sa.Column('is_revert', sa.Boolean(), nullable=False),
    sa.Column('files_changed', sa.Integer(), nullable=False),
    sa.Column('insertions', sa.Integer(), nullable=False),
    sa.Column('deletions', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commits_repo_id'), 'commits', ['repo_id'], unique=False)
    op.create_index('ix_commits_repo_id_sha', 'commits', ['repo_id', 'sha'], unique=False)
    op.create_index(op.f('ix_commits_sha'), 'commits', ['sha'], unique=False)
    op.create_table('coupling',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('file_a_path', sa.String(), nullable=False),
    sa.Column('file_b_path', sa.String(), nullable=False),
    sa.Column('shared_revs', sa.Integer(), nullable=False),
    sa.Column('coupling_degree', sa.Float(), nullable=False),
    sa.Column('avg_revs', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupling_repo_id'), 'coupling', ['repo_id'], unique=False)
    op.create_index('ix_coupling_repo_id_degree', 'coupling', ['repo_id', 'coupling_degree'], unique=False)
    op.create_table('dependencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('from_path', sa.String(), nullable=False),
    sa.Column('to_path', sa.String(), nullable=False),
    sa.Column('dep_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependencies_repo_id'), 'dependencies', ['repo_id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('current_loc', sa.Integer(), nullable=False),
    sa.Column('complexity', sa.Float(), nullable=False),
    sa.Column('churn_total', sa.Integer(), nullable=False),
    sa.Column('commit_count', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_repo_id'), 'files', ['repo_id'], unique=False)
    op.create_index('ix_files_repo_id_path', 'files', ['repo_id', 'path'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('severity', sa.Enum('low', 'med', 'high', name='finding_severity'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('evidence_sha', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_repo_id'), 'findings', ['repo_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=True),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'done', 'failed', name='job_status'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_repo_id'), 'jobs', ['repo_id'], unique=False)
    op.create_table('commit_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('commit_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['commit_id'], ['commits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_commit_files_commit_id', 'commit_files', ['commit_id'], unique=False)
    op.create_table('file_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_confidence', sa.Float(), nullable=True),
    sa.Column('hotspot_rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_metrics')
    op.drop_index('ix_commit_files_commit_id', table_name='commit_files')
    op.drop_table('commit_files')
    op.drop_index(op.f('ix_jobs_repo_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_findings_repo_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index('ix_files_repo_id_path', table_name='files')
    op.drop_index(op.f('ix_files_repo_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_dependencies_repo_id'), table_name='dependencies')
    op.drop_table('dependencies')
    op.drop_index('ix_coupling_repo_id_degree', table_name='coupling')
    op.drop_index(op.f('ix_coupling_repo_id'), table_name='coupling')
    op.drop_table('coupling')
    op.drop_index(op.f('ix_commits_sha'), table_name='commits')
    op.drop_index('ix_commits_repo_id_sha', table_name='commits')
    op.drop_index(op.f('ix_commits_repo_id'), table_name='commits')
    op.drop_table('commits')
    op.drop_index(op.f('ix_repos_url'), table_name='repos')
    op.drop_table('repos')
    op.drop_table('baselines')
    # ### end Alembic commands ###
